from fastapi import APIRouter, Depends, HTTPException, Response
from sqlalchemy.orm import Session
from app.database.database import get_db
from app.utils.auth import require_role
from app.models.users import Users
from app.utils.auth import require_role, get_current_user
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import io

router = APIRouter(prefix="/reports", tags=["Reports"])

@router.post("/generate")
def generate_report(
    data: dict, 
    db: Session = Depends(get_db),
    current_user: Users = Depends(get_current_user)
):
    # Data expected: { "student_name": "...", "subject": "...", "marks": "...", "remarks": "..." }
    
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)
    
    # Simple PDF Layout
    p.setFont("Helvetica-Bold", 16)
    p.drawString(100, 750, "DOZO STUDENT PROGRESS REPORT")
    
    p.setFont("Helvetica", 12)
    p.drawString(100, 720, f"Generated By: {current_user.name}")
    p.drawString(100, 705, f"Date: {current_user.created_at.strftime('%Y-%m-%d')}")
    
    p.line(100, 690, 500, 690)
    
    y = 660
    for key, value in data.items():
        p.drawString(100, y, f"{key.replace('_', ' ').capitalize()}: {value}")
        y -= 25
        
    p.showPage()
    p.save()
    
    buffer.seek(0)
    return Response(content=buffer.getvalue(), media_type="application/pdf", headers={
        "Content-Disposition": f"attachment; filename=report_{data.get('student_name', 'student')}.pdf"
    })
