from fastapi import APIRouter, Depends, HTTPException, Response
from sqlalchemy.orm import Session
from app.database.database import get_db
from app.utils.auth import require_role
from app.models.users import Users
from app.utils.auth import require_role, get_current_user
from app.schemas.reports import ReportRequest
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
import io
import logging
from datetime import datetime

router = APIRouter(prefix="/reports", tags=["Reports"])

# Configure logging
logger = logging.getLogger(__name__)

@router.post("/generate")
def generate_report(
    data: ReportRequest, 
    db: Session = Depends(get_db),
    current_user: Users = Depends(get_current_user)
):
    try:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
        styles = getSampleStyleSheet()
        
        # Custom Styles
        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor("#6366f1"),
            alignment=1, # Center
            spaceAfter=30,
            fontName='Helvetica-Bold'
        )
        
        header_style = ParagraphStyle(
            'HeaderStyle',
            parent=styles['Normal'],
            fontSize=12,
            textColor=colors.HexColor("#1e293b"),
            spaceAfter=12
        )

        section_style = ParagraphStyle(
            'SectionStyle',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor("#4f46e5"),
            spaceBefore=20,
            spaceAfter=10,
            fontName='Helvetica-Bold'
        )

        elements = []

        # Header Section
        elements.append(Paragraph("DOZO ACADEMIC REPORT", title_style))
        
        # Student & Generator Info
        gen_date = datetime.now().strftime('%B %d, %Y')
        elements.append(Paragraph(f"<b>Student Name:</b> {data.student_name}", header_style))
        elements.append(Paragraph(f"<b>Attendance:</b> {data.attendance}", header_style))
        elements.append(Paragraph(f"<b>Generated By:</b> {current_user.name}", header_style))
        elements.append(Paragraph(f"<b>Date:</b> {gen_date}", header_style))
        
        elements.append(Spacer(1, 0.2*inch))
        
        # Subject Performance Table
        elements.append(Paragraph("Subject Performance", section_style))
        
        subjects_data = [['Subject', 'Marks/Grade']]
        if data.subjects:
            for sub in data.subjects:
                subjects_data.append([sub.name or 'N/A', sub.marks or '-'])
        else:
            subjects_data.append(['No subjects provided', '-'])

        t = Table(subjects_data, colWidths=[4*inch, 1.5*inch])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#6366f1")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor("#f8fafc")),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor("#e2e8f0")),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('TOPPADDING', (0, 1), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ]))
        elements.append(t)
        
        # Remarks Section
        elements.append(Paragraph("Academic Remarks", section_style))
        remarks_text = data.remarks or 'No remarks provided.'
        elements.append(Paragraph(remarks_text, styles['Normal']))
        
        # Footer
        elements.append(Spacer(1, 1*inch))
        footer_style = ParagraphStyle('FooterStyle', parent=styles['Normal'], fontSize=8, textColor=colors.grey, alignment=1)
        elements.append(Paragraph("This is an electronically generated report from DOZO Academy Management System.", footer_style))

        doc.build(elements)
        
        buffer.seek(0)
        safe_filename = "".join([c for c in data.student_name if c.isalnum() or c in (' ', '_')]).rstrip()
        filename = f"Report_{safe_filename.replace(' ', '_')}.pdf"
        
        return Response(content=buffer.getvalue(), media_type="application/pdf", headers={
            "Content-Disposition": f"attachment; filename={filename}"
        })
    except Exception as e:
        logger.error(f"Error generating report: {str(e)}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to generate PDF: {str(e)}")
